name: ON-PUSH-MAIN
run-name: Continuous Integration ( ${{ github.event_name }} run by ${{ github.actor }} )

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - '.github/**'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:

  continuous-integration:
    name: CI on Main
    uses: dr3dr3/template-pipeline/.github/workflows/continuous-integration.yml@main
    if: ${{ github.event.head_commit.message != 'Initial commit' }}
    with: 
      feature: ${{ github.event.head_commit.message }}
      target-ref: ${{ github.sha }}
      solution: ${{ vars.SOLUTION }}
      deploy-to: ${{ vars.DEPLOY_CI }}
      repo-stage: ${{ vars.REPO_STAGE }}
      check-links: ${{ vars.CHECK_LINKS }}
    permissions:
      contents: write
      pages: write
      id-token: write
    secrets: inherit